Sp 49
GaneshNavale/stickify_client pull request #12
Opened 2024-10-04 18:29 UTC by Prasad1102

SP-49 : Admin Dashboard - Add Filter on Categories Page
SP-50 : Admin Dashboard - Cached Data in Descriptions Page
SP-51 : Admin Dashboard - Video Error

2024-10-04 18:51 UTC, GaneshNavale commented on src/components/data_management/Categories.jsx
> +      const isActive = selectedFilter === "active";
Use Server Side filtering

2024-10-04 18:55 UTC, GaneshNavale commented on src/components/data_management/DescriptionModal.jsx
> +            // sx={{ marginBottom: 4 }} will add in grid
remove

2024-10-04 18:57 UTC, GaneshNavale commented on src/components/data_management/DescriptionModal.jsx
> +        console.error("Video is not a file object:", description.video);
Check if we can utilize onChange event on media_type to reset video & images

2024-10-04 18:58 UTC, GaneshNavale requested changes
Please address the suggested changes.

2024-10-05 07:15 UTC, GaneshNavale commented on src/utils/VideoUploader.js
> +  }, [video]);
Remove

2024-10-05 08:34 UTC, Prasad1102 commented on src/utils/VideoUploader.js
> -      setLoading(false);
Changes Completed

2024-10-05 08:34 UTC, Prasad1102 commented on src/components/data_management/DescriptionModal.jsx
> +            // sx={{ marginBottom: 4 }} will add in grid
Changes are resolved

2024-10-05 08:34 UTC, Prasad1102 commented on src/utils/VideoUploader.js
> +  }, [video]);
changes are completed

2024-10-05 08:35 UTC, merged